module.exports = {
  baseUrl: 'https://rest.immobilienscout24.de/restapi/api/offer/v1.0/user/me/realestate',
  maxPixel: 3000,
  // TODO remove
  oauth_consumer_key: 'VHGruppeDeKey',
  consumer_secret: 'xyFnxSy1DtpqF47d',
  oauth_token: '5b376353-c9f5-4ed7-82ba-133954396341',
  oauth_token_secret: 'SP58GxWdtlEzS6x0nXmn4XyDPbr7wgpNHfSHhr2XVfztvNoJBueHVYa90nlvu27NpHHcGafGhaKiBsvaI3CdZ0FCE2KvBiG6K32JTZPHj5Y=',
  // EOF remove
  fields: [
    'furnishingNote',
    'locationNote',
    'otherNote',
    'descriptionNote',
    'firingTypes',
    'constructionYear',
    'condition',
    'constructionPhase',
    'lastRefurbishment',
    'interiorQuality',
    'freeFrom',
    'rented',
    'livingSpace',
    'floor',
    'courtage',
    'numberOfFloors',
    'totalFloorSpace',
    'usableFloorSpace',
    'netFloorSpace',
    'plotArea',
    'numberOfApartments',
    'numberOfRooms',
    'numberOfBedRooms',
    'numberOfBathRooms',
    'bathHasShower',
    'bathHasTub',
    'bathHasWc',
    'guestToilet',
    'distanceToAirport',
    'distanceToFM',
    'distanceToMRS',
    'distanceToPT',
    'heatingType',
    'buildingEnergyRatingType',
    'energyConsumptionContainsWarmWater',
    'energyConsumptionElectricity',
    'energyConsumptionHeating',
    'energyEfficiencyClass',
    'energyPerformanceCertificate',
    'listed',
    'numberOfParkingSpaces',
    'parkingSpacePrice',
    'parkingSpaceType',
    'parkingSituation',
    'cellar',
    'balcony',
    'garden',
    'furnishing',
    'builtInKitchen',
    'tvConnection',
    'dishwasher',
    'washingMachine',
    'oven',
    'refrigerator',
    'stove',
    'internetConnection',
    'telephoneConnection',
    'electricityConsumption',
    'thermalCharacteristic',
    'thermalCharacteristicElectricity',
    'thermalCharacteristicHeating',
    'certificateOfEligibilityNeeded',
    'flatShareSize',
    'heatingConsumption',
    'LivingInformation',
    'requestedGender',
    'smokingAllowed',
    'lodgerFlat',
    'handicappedAccessible',
    'summerResidencePractical',
  ],
};
